# Generated by Django 2.2.6 on 2020-02-12 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Donaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='donante',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='Donaciones.Donante'),
        ),
    ]
