# Generated by Django 2.2.6 on 2020-02-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donaciones', '0003_listaapellidos_listanombres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listaapellidos',
            options={'verbose_name': 'Lista de Apellidos', 'verbose_name_plural': 'ListaApellidoss'},
        ),
        migrations.AlterModelOptions(
            name='listanombres',
            options={'verbose_name': 'Lista de Nombres', 'verbose_name_plural': 'ListaNombress'},
        ),
        migrations.RemoveField(
            model_name='donante',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='donante',
            name='nombres',
        ),
        migrations.AddField(
            model_name='donante',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Primer Apellido'),
        ),
        migrations.AddField(
            model_name='donante',
            name='primer_nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Primer Nombre'),
        ),
        migrations.AddField(
            model_name='donante',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo Apellido'),
        ),
        migrations.AddField(
            model_name='donante',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo Nombre'),
        ),
        migrations.AlterField(
            model_name='listaapellidos',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
    ]
