# Generated by Django 2.2.6 on 2020-05-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donaciones', '0004_auto_20200227_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoCarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(max_length=200, upload_to='static/cargas/', verbose_name='Archivo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga')),
            ],
            options={
                'verbose_name': 'Archivo de Carga',
                'verbose_name_plural': 'Archivos de Carga',
            },
        ),
    ]
