# Generated by Django 2.2.6 on 2020-05-04 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Donaciones', '0005_archivocarga'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='carga',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Donaciones.ArchivoCarga', verbose_name='Id_Carga'),
            preserve_default=False,
        ),
    ]
