# Generated by Django 2.2.6 on 2020-01-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('artist', models.CharField(blank=True, max_length=40, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, choices=[('R', 'Rock'), ('B', 'Blues'), ('J', 'Jazz'), ('P', 'Pop'), ('Rg', 'Reggae')], max_length=3, null=True)),
            ],
        ),
    ]
